In [6]:
import numpy as np
import pandas as pd
import matplotlib

Month = np.array(["Jan","Feb","Mar"])
print(Month)

ProductA = np.array([120,130,125])
print(ProductA)

ProductB = np.array([150,160,170])
print(ProductB)

ProductC = np.array([100,110,105])
print(ProductC)

['Wah' 'Feb' 'Mar']
[120 130 125]
[150 160 170]
[100 110 105]


In [7]:
df = pd.Dataframe{ProductA

<class 'AttributeError'>: module 'pandas' has no attribute 'ProductA'